# Generated by Django 4.2.1 on 2023-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_remove_publisher_name_remove_reader_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
