# Generated by Django 4.2.1 on 2023-05-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='comment',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
    ]
